[browser]
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[runner]
fastRerenderThreshold = 1000

[client]
toolbarMode = "minimal"
showErrorDetails = true

[telemetry]
enabled = false 